/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://ymgcdsvt6jdwddtjqiiukxnugm.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cognito_identity_pool_id": "us-east-1:16179455-f455-4f5a-964a-fa7e9a50c183",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_zRHGpf4Ev",
    "aws_user_pools_web_client_id": "3k48hepto3as67fhsjo60dslee",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "nutritionappba9b6c4ca45149ff8061ef85f03d2a51152757-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
